// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.ac.bbk.bookface.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import uk.ac.bbk.bookface.domain.Author;
import uk.ac.bbk.bookface.domain.AuthorDataOnDemand;

privileged aspect AuthorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AuthorDataOnDemand: @Component;
    
    private Random AuthorDataOnDemand.rnd = new SecureRandom();
    
    private List<Author> AuthorDataOnDemand.data;
    
    public Author AuthorDataOnDemand.getNewTransientAuthor(int index) {
        Author obj = new Author();
        setIdentifier(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AuthorDataOnDemand.setIdentifier(Author obj, int index) {
        Number identifier = null;
        obj.setIdentifier(identifier);
    }
    
    public void AuthorDataOnDemand.setName(Author obj, int index) {
        String name = "name_" + index;
        if (name.length() > 255) {
            name = name.substring(0, 255);
        }
        obj.setName(name);
    }
    
    public Author AuthorDataOnDemand.getSpecificAuthor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Author obj = data.get(index);
        Long id = obj.getId();
        return Author.findAuthor(id);
    }
    
    public Author AuthorDataOnDemand.getRandomAuthor() {
        init();
        Author obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Author.findAuthor(id);
    }
    
    public boolean AuthorDataOnDemand.modifyAuthor(Author obj) {
        return false;
    }
    
    public void AuthorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Author.findAuthorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Author' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Author>();
        for (int i = 0; i < 10; i++) {
            Author obj = getNewTransientAuthor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
