// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.ac.bbk.bookface.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import uk.ac.bbk.bookface.domain.BookFaceUser;
import uk.ac.bbk.bookface.domain.BookFaceUserDataOnDemand;
import uk.ac.bbk.bookface.domain.BookFaceUserIntegrationTest;

privileged aspect BookFaceUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BookFaceUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BookFaceUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BookFaceUserIntegrationTest: @Transactional;
    
    @Autowired
    BookFaceUserDataOnDemand BookFaceUserIntegrationTest.dod;
    
    @Test
    public void BookFaceUserIntegrationTest.testCountBookFaceUsers() {
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", dod.getRandomBookFaceUser());
        long count = BookFaceUser.countBookFaceUsers();
        Assert.assertTrue("Counter for 'BookFaceUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testFindBookFaceUser() {
        BookFaceUser obj = dod.getRandomBookFaceUser();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to provide an identifier", id);
        obj = BookFaceUser.findBookFaceUser(id);
        Assert.assertNotNull("Find method for 'BookFaceUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BookFaceUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testFindAllBookFaceUsers() {
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", dod.getRandomBookFaceUser());
        long count = BookFaceUser.countBookFaceUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'BookFaceUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BookFaceUser> result = BookFaceUser.findAllBookFaceUsers();
        Assert.assertNotNull("Find all method for 'BookFaceUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BookFaceUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testFindBookFaceUserEntries() {
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", dod.getRandomBookFaceUser());
        long count = BookFaceUser.countBookFaceUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BookFaceUser> result = BookFaceUser.findBookFaceUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BookFaceUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BookFaceUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testFlush() {
        BookFaceUser obj = dod.getRandomBookFaceUser();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to provide an identifier", id);
        obj = BookFaceUser.findBookFaceUser(id);
        Assert.assertNotNull("Find method for 'BookFaceUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBookFaceUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BookFaceUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testMergeUpdate() {
        BookFaceUser obj = dod.getRandomBookFaceUser();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to provide an identifier", id);
        obj = BookFaceUser.findBookFaceUser(id);
        boolean modified =  dod.modifyBookFaceUser(obj);
        Integer currentVersion = obj.getVersion();
        BookFaceUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BookFaceUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", dod.getRandomBookFaceUser());
        BookFaceUser obj = dod.getNewTransientBookFaceUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BookFaceUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BookFaceUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BookFaceUserIntegrationTest.testRemove() {
        BookFaceUser obj = dod.getRandomBookFaceUser();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BookFaceUser' failed to provide an identifier", id);
        obj = BookFaceUser.findBookFaceUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BookFaceUser' with identifier '" + id + "'", BookFaceUser.findBookFaceUser(id));
    }
    
}
