// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.ac.bbk.bookface.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import uk.ac.bbk.bookface.domain.BookFaceUser;
import uk.ac.bbk.bookface.domain.BookFaceUserDataOnDemand;
import uk.ac.bbk.bookface.domain.PersonDataOnDemand;

privileged aspect BookFaceUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BookFaceUserDataOnDemand: @Component;
    
    private Random BookFaceUserDataOnDemand.rnd = new SecureRandom();
    
    private List<BookFaceUser> BookFaceUserDataOnDemand.data;
    
    @Autowired
    PersonDataOnDemand BookFaceUserDataOnDemand.personDataOnDemand;
    
    public BookFaceUser BookFaceUserDataOnDemand.getNewTransientBookFaceUser(int index) {
        BookFaceUser obj = new BookFaceUser();
        setIdentifier(obj, index);
        return obj;
    }
    
    public void BookFaceUserDataOnDemand.setIdentifier(BookFaceUser obj, int index) {
        Number identifier = null;
        obj.setIdentifier(identifier);
    }
    
    public BookFaceUser BookFaceUserDataOnDemand.getSpecificBookFaceUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BookFaceUser obj = data.get(index);
        Long id = obj.getId();
        return BookFaceUser.findBookFaceUser(id);
    }
    
    public BookFaceUser BookFaceUserDataOnDemand.getRandomBookFaceUser() {
        init();
        BookFaceUser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return BookFaceUser.findBookFaceUser(id);
    }
    
    public boolean BookFaceUserDataOnDemand.modifyBookFaceUser(BookFaceUser obj) {
        return false;
    }
    
    public void BookFaceUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BookFaceUser.findBookFaceUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BookFaceUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BookFaceUser>();
        for (int i = 0; i < 10; i++) {
            BookFaceUser obj = getNewTransientBookFaceUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
