// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.ac.bbk.bookface.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import uk.ac.bbk.bookface.domain.Comments;
import uk.ac.bbk.bookface.domain.CommentsDataOnDemand;
import uk.ac.bbk.bookface.domain.CommentsIntegrationTest;

privileged aspect CommentsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CommentsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CommentsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CommentsIntegrationTest: @Transactional;
    
    @Autowired
    CommentsDataOnDemand CommentsIntegrationTest.dod;
    
    @Test
    public void CommentsIntegrationTest.testCountCommentses() {
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", dod.getRandomComments());
        long count = Comments.countCommentses();
        Assert.assertTrue("Counter for 'Comments' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CommentsIntegrationTest.testFindComments() {
        Comments obj = dod.getRandomComments();
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comments' failed to provide an identifier", id);
        obj = Comments.findComments(id);
        Assert.assertNotNull("Find method for 'Comments' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Comments' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CommentsIntegrationTest.testFindAllCommentses() {
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", dod.getRandomComments());
        long count = Comments.countCommentses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Comments', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Comments> result = Comments.findAllCommentses();
        Assert.assertNotNull("Find all method for 'Comments' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Comments' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CommentsIntegrationTest.testFindCommentsEntries() {
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", dod.getRandomComments());
        long count = Comments.countCommentses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Comments> result = Comments.findCommentsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Comments' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Comments' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CommentsIntegrationTest.testFlush() {
        Comments obj = dod.getRandomComments();
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comments' failed to provide an identifier", id);
        obj = Comments.findComments(id);
        Assert.assertNotNull("Find method for 'Comments' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyComments(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Comments' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommentsIntegrationTest.testMergeUpdate() {
        Comments obj = dod.getRandomComments();
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comments' failed to provide an identifier", id);
        obj = Comments.findComments(id);
        boolean modified =  dod.modifyComments(obj);
        Integer currentVersion = obj.getVersion();
        Comments merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Comments' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CommentsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", dod.getRandomComments());
        Comments obj = dod.getNewTransientComments(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Comments' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Comments' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Comments' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CommentsIntegrationTest.testRemove() {
        Comments obj = dod.getRandomComments();
        Assert.assertNotNull("Data on demand for 'Comments' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Comments' failed to provide an identifier", id);
        obj = Comments.findComments(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Comments' with identifier '" + id + "'", Comments.findComments(id));
    }
    
}
