// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.ac.bbk.bookface.domain;

import org.springframework.beans.factory.annotation.Configurable;
import uk.ac.bbk.bookface.domain.CommentsIntegrationTest;

privileged aspect CommentsIntegrationTest_Roo_Configurable {
    
    declare @type: CommentsIntegrationTest: @Configurable;
    
}
