// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ac.uk.bbk.bookface.domain;

import ac.uk.bbk.bookface.domain.Book;
import ac.uk.bbk.bookface.domain.BookDataOnDemand;
import ac.uk.bbk.bookface.domain.Comments;
import ac.uk.bbk.bookface.domain.CommentsDataOnDemand;
import ac.uk.bbk.bookface.domain.Person;
import ac.uk.bbk.bookface.domain.PersonDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CommentsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CommentsDataOnDemand: @Component;
    
    private Random CommentsDataOnDemand.rnd = new SecureRandom();
    
    private List<Comments> CommentsDataOnDemand.data;
    
    @Autowired
    BookDataOnDemand CommentsDataOnDemand.bookDataOnDemand;
    
    @Autowired
    PersonDataOnDemand CommentsDataOnDemand.personDataOnDemand;
    
    public Comments CommentsDataOnDemand.getNewTransientComments(int index) {
        Comments obj = new Comments();
        setBook(obj, index);
        setDescription(obj, index);
        setIdentifier(obj, index);
        setPerson(obj, index);
        return obj;
    }
    
    public void CommentsDataOnDemand.setBook(Comments obj, int index) {
        Book book = bookDataOnDemand.getRandomBook();
        obj.setBook(book);
    }
    
    public void CommentsDataOnDemand.setDescription(Comments obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void CommentsDataOnDemand.setIdentifier(Comments obj, int index) {
        Number identifier = null;
        obj.setIdentifier(identifier);
    }
    
    public void CommentsDataOnDemand.setPerson(Comments obj, int index) {
        Person person = personDataOnDemand.getRandomPerson();
        obj.setPerson(person);
    }
    
    public Comments CommentsDataOnDemand.getSpecificComments(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Comments obj = data.get(index);
        Long id = obj.getId();
        return Comments.findComments(id);
    }
    
    public Comments CommentsDataOnDemand.getRandomComments() {
        init();
        Comments obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Comments.findComments(id);
    }
    
    public boolean CommentsDataOnDemand.modifyComments(Comments obj) {
        return false;
    }
    
    public void CommentsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Comments.findCommentsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Comments' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Comments>();
        for (int i = 0; i < 10; i++) {
            Comments obj = getNewTransientComments(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
