// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ac.uk.bbk.bookface.domain;

import ac.uk.bbk.bookface.domain.CommentsDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CommentsDataOnDemand_Roo_Configurable {
    
    declare @type: CommentsDataOnDemand: @Configurable;
    
}
