// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ac.uk.bbk.bookface.domain;

import ac.uk.bbk.bookface.domain.Favourites;
import ac.uk.bbk.bookface.domain.FavouritesDataOnDemand;
import ac.uk.bbk.bookface.domain.FavouritesIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FavouritesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FavouritesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FavouritesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FavouritesIntegrationTest: @Transactional;
    
    @Autowired
    FavouritesDataOnDemand FavouritesIntegrationTest.dod;
    
    @Test
    public void FavouritesIntegrationTest.testCountFavouriteses() {
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", dod.getRandomFavourites());
        long count = Favourites.countFavouriteses();
        Assert.assertTrue("Counter for 'Favourites' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FavouritesIntegrationTest.testFindFavourites() {
        Favourites obj = dod.getRandomFavourites();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to provide an identifier", id);
        obj = Favourites.findFavourites(id);
        Assert.assertNotNull("Find method for 'Favourites' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Favourites' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FavouritesIntegrationTest.testFindAllFavouriteses() {
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", dod.getRandomFavourites());
        long count = Favourites.countFavouriteses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Favourites', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Favourites> result = Favourites.findAllFavouriteses();
        Assert.assertNotNull("Find all method for 'Favourites' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Favourites' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FavouritesIntegrationTest.testFindFavouritesEntries() {
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", dod.getRandomFavourites());
        long count = Favourites.countFavouriteses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Favourites> result = Favourites.findFavouritesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Favourites' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Favourites' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FavouritesIntegrationTest.testFlush() {
        Favourites obj = dod.getRandomFavourites();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to provide an identifier", id);
        obj = Favourites.findFavourites(id);
        Assert.assertNotNull("Find method for 'Favourites' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFavourites(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Favourites' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FavouritesIntegrationTest.testMergeUpdate() {
        Favourites obj = dod.getRandomFavourites();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to provide an identifier", id);
        obj = Favourites.findFavourites(id);
        boolean modified =  dod.modifyFavourites(obj);
        Integer currentVersion = obj.getVersion();
        Favourites merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Favourites' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FavouritesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", dod.getRandomFavourites());
        Favourites obj = dod.getNewTransientFavourites(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Favourites' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Favourites' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Favourites' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FavouritesIntegrationTest.testRemove() {
        Favourites obj = dod.getRandomFavourites();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Favourites' failed to provide an identifier", id);
        obj = Favourites.findFavourites(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Favourites' with identifier '" + id + "'", Favourites.findFavourites(id));
    }
    
}
