// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ac.uk.bbk.bookface.domain;

import ac.uk.bbk.bookface.domain.Person;

privileged aspect Person_Roo_JavaBean {
    
    public String Person.getEmailAddress() {
        return this.emailAddress;
    }
    
    public void Person.setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
}
